# Generated by Django 2.1.4 on 2019-02-03 10:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Attendance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DivisionSubject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='div',
            name='division',
            field=models.CharField(max_length=10),
        ),
        migrations.AddField(
            model_name='divisionsubject',
            name='division',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Attendance.Div'),
        ),
        migrations.AddField(
            model_name='divisionsubject',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Attendance.Subject'),
        ),
        migrations.AddField(
            model_name='div',
            name='subject',
            field=models.ManyToManyField(related_name='division', through='Attendance.DivisionSubject', to='Attendance.Subject'),
        ),
    ]
