# Generated by Django 2.1.4 on 2019-02-03 10:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Attendance', '0002_auto_20190203_1547'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentDivision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('division', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Attendance.Div')),
            ],
        ),
        migrations.RenameField(
            model_name='lecture',
            old_name='lectureClass',
            new_name='div',
        ),
        migrations.RemoveField(
            model_name='student',
            name='div',
        ),
        migrations.AddField(
            model_name='studentdivision',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Attendance.Student'),
        ),
        migrations.AddField(
            model_name='student',
            name='div',
            field=models.ManyToManyField(related_name='student', through='Attendance.StudentDivision', to='Attendance.Div'),
        ),
    ]
